services:
  - type: web
    name: doc-query-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DEBUG
        value: "false"
      - key: GEMINI_API_KEY
        sync: false
